import React, { useState, useEffect, useCallback } from 'react';
import Layout from '../components/layout/Layout';
import api from '../api/api';

const fmtKES = (n) => {
  const v = typeof n === 'string' ? parseFloat(n) : n;
  if (!Number.isFinite(v)) return '0.00';
  return v.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

const fmtDate = (iso) => iso
  ? new Date(iso).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
  : '—';

const STATUS_META = {
  draft: { label: 'Draft', tone: 'bg-amber-50 text-amber-700 border-amber-200' },
  sent:  { label: 'Sent',  tone: 'bg-blue-50 text-blue-700 border-blue-200' },
  paid:  { label: 'Paid',  tone: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
  void:  { label: 'Void',  tone: 'bg-slate-100 text-slate-500 border-slate-200' },
};

const STATUS_TABS = ['all', 'draft', 'sent', 'paid', 'void'];

const emptySummary = { draft: { count: 0, totalAmount: 0 }, sent: { count: 0, totalAmount: 0 }, paid: { count: 0, totalAmount: 0 }, void: { count: 0, totalAmount: 0 }, overdue: { count: 0, totalAmount: 0 } };

const isOverdue = (inv) => inv.status === 'sent' && inv.dueDate && new Date(inv.dueDate).getTime() < Date.now();

const daysOverdue = (dueDate) => Math.max(1, Math.ceil((Date.now() - new Date(dueDate).getTime()) / (1000 * 60 * 60 * 24)));

const Invoices = () => {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [invoices, setInvoices] = useState([]);
  const [summary, setSummary] = useState(emptySummary);

  const [status, setStatus] = useState('all');
  const [searchInput, setSearchInput] = useState('');
  const [q, setQ] = useState('');
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [total, setTotal] = useState(0);
  const limit = 25;

  const fetchInvoices = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const res = await api.get('/api/admin/invoices', { params: { page, limit, status, q } });
      if (res.data?.success) {
        setInvoices(res.data.invoices || []);
        setSummary(res.data.summary || summary);
        setTotalPages(res.data.totalPages || 1);
        setTotal(res.data.total || 0);
      } else {
        setError(res.data?.error || 'Could not load invoices.');
      }
    } catch (err) {
      setError(err?.response?.data?.error || err?.message || 'Could not load invoices.');
    } finally {
      setLoading(false);
    }
  }, [page, status, q]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => { fetchInvoices(); }, [fetchInvoices]);

  useEffect(() => {
    const t = setTimeout(() => { setQ(searchInput.trim()); setPage(1); }, 400);
    return () => clearTimeout(t);
  }, [searchInput]);

  return (
    <Layout>
      <div className="space-y-8 pb-12">
        {/* Header Hero */}
        <div className="relative overflow-hidden rounded-3xl bg-[#061121] border border-[#1A2639] shadow-[0_30px_80px_-20px_rgba(6,17,33,0.8)] p-6 md:p-10">
          <div className="absolute -top-32 -right-32 w-[500px] h-[500px] bg-emerald-500/10 rounded-full blur-[100px]"></div>
          <div className="absolute -bottom-24 -left-24 w-[400px] h-[400px] bg-blue-500/10 rounded-full blur-[80px]"></div>

          <div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-6">
            <div>
              <div className="flex items-center gap-3 mb-3">
                <span className="relative flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-emerald-500"></span>
                </span>
                <p className="text-2xs font-bold uppercase tracking-[0.3em] text-emerald-400">Platform-Wide Billing</p>
              </div>
              <h2 className="text-4xl md:text-5xl font-bold text-white tracking-tighter font-headline leading-tight">
                Invoices
              </h2>
              <p className="text-xs md:text-sm text-blue-100/60 mt-2 max-w-2xl font-body">
                Every invoice generated by every merchant on PayChain — track drafts, sends, and follow-ups from one register.
              </p>
            </div>
            <button
              onClick={fetchInvoices}
              disabled={loading}
              className="group self-start md:self-auto flex items-center gap-2 px-5 py-3 bg-white/5 hover:bg-white/10 backdrop-blur-md border border-white/10 text-white text-xs font-bold rounded-xl uppercase tracking-widest transition-all disabled:opacity-50"
            >
              <span className={`material-symbols-outlined text-lg group-hover:rotate-180 transition-transform duration-500 ${loading ? 'animate-spin' : ''}`}>sync</span>
              Refresh
            </button>
          </div>
        </div>

        {/* Summary Cards */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
          <SummaryCard
            label="Total Invoices"
            value={total}
            subtitle="Across every merchant"
            icon="receipt_long"
            tone="slate"
          />
          <SummaryCard
            label="Awaiting Payment"
            value={`KES ${fmtKES(summary.sent.totalAmount)}`}
            subtitle={`${summary.sent.count} sent invoice${summary.sent.count === 1 ? '' : 's'}`}
            icon="schedule_send"
            tone="sky"
          />
          <SummaryCard
            label="Overdue"
            value={`KES ${fmtKES(summary.overdue.totalAmount)}`}
            subtitle={`${summary.overdue.count} past due date`}
            icon="warning"
            tone="rose"
            highlight={summary.overdue.count > 0}
          />
          <SummaryCard
            label="Drafts"
            value={summary.draft.count}
            subtitle="Not yet sent"
            icon="edit_note"
            tone="amber"
          />
        </div>

        {/* Table */}
        <div className="bg-surface-container-lowest rounded-3xl border border-outline-variant/20 shadow-editorial overflow-hidden">
          <div className="px-6 py-5 border-b border-outline-variant/10 bg-white/50 backdrop-blur-xl flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-lg font-black text-on-surface tracking-tight">All Invoices</h3>
              <p className="text-xs text-on-surface-variant/60 font-medium">Across every merchant account</p>
            </div>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3">
              <div className="relative">
                <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-base text-slate-400">search</span>
                <input
                  value={searchInput}
                  onChange={(e) => setSearchInput(e.target.value)}
                  placeholder="Invoice #, customer name or email..."
                  className="pl-9 pr-3 py-2 border border-outline-variant/40 rounded-lg text-xs font-medium bg-white w-full sm:w-64"
                />
              </div>
              <div className="flex gap-1 p-1 bg-white border border-outline-variant/20 rounded-xl overflow-x-auto no-scrollbar">
                {STATUS_TABS.map(s => (
                  <button
                    key={s}
                    onClick={() => { setStatus(s); setPage(1); }}
                    className={`px-3 py-1.5 text-2xs font-black uppercase tracking-widest rounded-lg whitespace-nowrap transition-all ${
                      status === s ? 'bg-[#06201B] text-white' : 'text-slate-500 hover:text-primary'
                    }`}
                  >
                    {s === 'all' ? 'All' : STATUS_META[s]?.label || s}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {error ? (
            <div className="p-6 text-center text-red-500 text-sm font-bold">{error}</div>
          ) : (
            <div className="overflow-x-auto custom-scrollbar">
              <table className="w-full text-left font-body min-w-[900px]">
                <thead>
                  <tr className="bg-surface-container-low/30 border-b border-outline-variant/10">
                    <Th className="pl-6">Invoice</Th>
                    <Th>Merchant</Th>
                    <Th>Customer</Th>
                    <Th className="text-right">Amount</Th>
                    <Th>Status</Th>
                    <Th>Issued</Th>
                    <Th className="pr-6">Due</Th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-outline-variant/5">
                  {loading ? (
                    <tr><td colSpan="7" className="px-6 py-16 text-center">
                      <div className="inline-flex flex-col items-center gap-4">
                        <div className="relative w-12 h-12">
                          <div className="absolute inset-0 rounded-full border-2 border-emerald-500/20"></div>
                          <div className="absolute inset-0 rounded-full border-2 border-emerald-500 border-t-transparent animate-spin"></div>
                        </div>
                        <span className="text-xs font-bold text-on-surface-variant uppercase tracking-widest">Loading invoices...</span>
                      </div>
                    </td></tr>
                  ) : invoices.length === 0 ? (
                    <tr><td colSpan="7" className="px-6 py-12 text-center text-on-surface-variant/40 text-sm font-medium">No invoices match this filter.</td></tr>
                  ) : invoices.map((inv) => <InvoiceRow key={inv._id} inv={inv} />)}
                </tbody>
              </table>
            </div>
          )}

          {!loading && !error && totalPages > 1 && (
            <div className="px-6 py-4 border-t border-outline-variant/10 flex items-center justify-between">
              <p className="text-2xs font-bold text-on-surface-variant/60">Page {page} of {totalPages} • {total} total</p>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setPage(p => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="w-8 h-8 rounded-full flex items-center justify-center bg-white border border-outline-variant/20 text-primary shadow-sm hover:bg-primary hover:text-white disabled:opacity-20 transition-all"
                >
                  <span className="material-symbols-outlined text-lg">chevron_left</span>
                </button>
                <button
                  onClick={() => setPage(p => Math.min(totalPages, p + 1))}
                  disabled={page >= totalPages}
                  className="w-8 h-8 rounded-full flex items-center justify-center bg-white border border-outline-variant/20 text-primary shadow-sm hover:bg-primary hover:text-white disabled:opacity-20 transition-all"
                >
                  <span className="material-symbols-outlined text-lg">chevron_right</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </Layout>
  );
};

const InvoiceRow = ({ inv }) => {
  const meta = STATUS_META[inv.status] || { label: inv.status, tone: 'bg-slate-100 text-slate-500 border-slate-200' };
  return (
    <tr className="hover:bg-surface-container-lowest transition-colors bg-white">
      <td className="px-6 py-4">
        <span className="text-xs font-mono font-bold text-on-surface">#{inv.invoiceNumber}</span>
      </td>
      <td className="px-3 py-4">
        <span className="text-xs font-bold text-on-surface tracking-tight">{inv.merchant?.businessName || '—'}</span>
        <p className="text-2xs text-on-surface-variant/50">{inv.merchant?.email}</p>
      </td>
      <td className="px-3 py-4">
        <span className="text-xs font-medium text-on-surface">{inv.customer?.name || 'Unnamed Customer'}</span>
        <p className="text-2xs text-on-surface-variant/50 truncate max-w-[180px]">{inv.customer?.email || '—'}</p>
      </td>
      <td className="px-3 py-4 text-right">
        <span className="text-sm font-bold text-on-surface tabular-nums">{inv.currency} {fmtKES(inv.total)}</span>
      </td>
      <td className="px-3 py-4">
        <span className={`inline-flex items-center px-2.5 py-1 rounded-full text-2xs font-bold uppercase tracking-widest border ${meta.tone}`}>
          {meta.label}
        </span>
      </td>
      <td className="px-3 py-4">
        <span className="text-xs font-medium text-slate-500">{fmtDate(inv.issueDate || inv.createdAt)}</span>
      </td>
      <td className="px-3 py-4 pr-6">
        {inv.dueDate ? (
          isOverdue(inv) ? (
            <span className="inline-flex items-center gap-1 text-2xs font-bold text-rose-600">
              <span className="material-symbols-outlined text-sm">warning</span>
              {daysOverdue(inv.dueDate)}d overdue
            </span>
          ) : (
            <span className="text-xs font-medium text-slate-500">{fmtDate(inv.dueDate)}</span>
          )
        ) : (
          <span className="text-2xs text-slate-300">—</span>
        )}
      </td>
    </tr>
  );
};

const Th = ({ children, className = '' }) => (
  <th className={`px-3 py-4 text-2xs font-black uppercase tracking-[0.15em] text-slate-400 ${className}`}>{children}</th>
);

const SUMMARY_TONE = {
  slate: 'bg-slate-100 text-slate-600',
  sky: 'bg-sky-50 text-sky-600',
  rose: 'bg-rose-50 text-rose-600',
  amber: 'bg-amber-50 text-amber-600',
};

const SummaryCard = ({ label, value, subtitle, icon, tone, highlight }) => (
  <div className={`p-5 rounded-2xl border shadow-sm transition-transform hover:-translate-y-1 ${highlight ? 'bg-rose-50/40 border-rose-200' : 'bg-surface-container-lowest border-outline-variant/20'}`}>
    <div className="flex items-start justify-between gap-3">
      <div className="min-w-0">
        <span className="text-2xs font-bold uppercase tracking-[0.15em] text-on-surface-variant/50 block mb-2">{label}</span>
        <span className="text-2xl md:text-3xl font-black text-on-surface tracking-tighter tabular-nums block truncate">{value}</span>
        <span className={`text-2xs font-bold mt-1 block ${highlight ? 'text-rose-600' : 'text-on-surface-variant/50'}`}>{subtitle}</span>
      </div>
      <div className={`grid h-10 w-10 shrink-0 place-items-center rounded-full ${SUMMARY_TONE[tone] || SUMMARY_TONE.slate}`}>
        <span className="material-symbols-outlined text-xl">{icon}</span>
      </div>
    </div>
  </div>
);

export default Invoices;
