import React from "react";
import { Link } from "react-router-dom";
import { Download, FileJson, Send } from "lucide-react";
import CodeBlock from "@/components/CodeBlock";
import Callout from "@/components/Callout";

function DownloadCard({ icon: Icon, title, desc, href, file }: { icon: React.ComponentType<{ className?: string }>; title: string; desc: string; href: string; file: string }) {
  return (
    <a
      href={href}
      download={file}
      className="group flex items-start gap-3 p-4 rounded-xl border border-border bg-surface hover:border-brand/30 hover:bg-surface-raised transition-all no-underline"
    >
      <div className="w-9 h-9 rounded-lg bg-brand/10 border border-brand/20 flex items-center justify-center shrink-0">
        <Icon className="w-4 h-4 text-brand-bright" />
      </div>
      <div className="min-w-0">
        <div className="text-[14px] font-semibold text-ink flex items-center gap-1.5">{title}<Download className="w-3.5 h-3.5 text-ink-faint group-hover:text-brand-bright" /></div>
        <div className="text-[12.5px] text-ink-muted leading-5 mt-0.5">{desc}</div>
        <div className="text-[11.5px] font-mono text-ink-faint mt-1">{file}</div>
      </div>
    </a>
  );
}

export default function ApiReference() {
  return (
    <>
      <h1 className="text-3xl font-extrabold text-ink tracking-tight mb-4">OpenAPI and Postman</h1>
      <p>
        The whole public API in two files. Import them to try every endpoint from your browser or desktop, or to
        generate a client library in your own language.
      </p>

      <div className="grid sm:grid-cols-2 gap-3 mt-6 mb-8">
        <DownloadCard icon={Send} title="Postman collection" desc="Every request ready to send. Saves ids for you as you go." href="/paychain.postman_collection.json" file="paychain.postman_collection.json" />
        <DownloadCard icon={FileJson} title="OpenAPI 3.0 spec" desc="The machine-readable description of every endpoint, request and response." href="/openapi.json" file="openapi.json" />
      </div>

      <h2>Use the Postman collection</h2>
      <ol className="list-decimal pl-5 space-y-1 text-[15px] leading-7 text-ink-muted mb-4">
        <li>In Postman choose <strong>Import</strong> and select the file.</li>
        <li>Open the collection's <strong>Variables</strong> tab and put your <Link to="/dashboard/api-keys">test key</Link> (<code>pc_test_…</code>) in <code>apiKey</code>.</li>
        <li>Send <strong>Check your API key</strong>. A 200 means you are set.</li>
        <li>Send <strong>Collect a payment</strong>. It creates a fresh Idempotency-Key for you and saves the payment id, so <strong>Get a payment</strong> works next with no copying.</li>
      </ol>
      <Callout variant="warning" title="Keep live keys out of shared workspaces">
        Use a test key while exploring. If you put a live key in Postman, do not sync that collection to a team
        workspace, because it can move real money.
      </Callout>

      <h2>Generate a client library</h2>
      <p>Any OpenAPI tool can turn the spec into a typed client. For example:</p>
      <CodeBlock
        lang="bash"
        code={`# TypeScript types
npx openapi-typescript https://developer.paychain.co.ke/openapi.json -o paychain.d.ts

# A full client (PHP, Python, Java, Go, and more)
npx @openapitools/openapi-generator-cli generate \\
  -i https://developer.paychain.co.ke/openapi.json -g php -o ./paychain-php`}
      />
      <p className="text-[13.5px] text-ink-muted leading-6">
        These are generated by third-party tools, so try them in the sandbox first. Plain REST from any language
        works too: see the <Link to="/quickstart">Quickstart</Link>.
      </p>

      <h2>What is inside</h2>
      <ul>
        <li>12 operations: ping, collect, payout, get payment, hosted checkout (create and get), invoices (create, list, get, send), bulk payments (create and get).</li>
        <li>The error format, the <code>Idempotency-Key</code> header, and the rate limits.</li>
        <li>The webhook event names and how to check the signature. The payloads themselves are in the <Link to="/webhooks">Webhooks guide</Link>.</li>
      </ul>
    </>
  );
}
