export const FAQ_DATA = [
  {
    id: 'getting-started',
    category: 'Getting Started',
    icon: 'Compass',
    questions: [
      { id: 'q1', q: 'What exactly is PayChain?', a: `PayChain is a hybrid merchant operating system built for Kenyan SMEs. It gives you a single dashboard to collect payments securely through a verified PayChain Virtual Account, pay staff and suppliers in bulk, swap KES to USDC to protect against shilling depreciation, and access working capital based on your real transaction history — all without collateral, bank queues, or complex paperwork.` },
      { id: 'q2', q: 'Who is PayChain built for?', a: `PayChain is built for any Kenyan business that collects payments, pays staff or suppliers, deals with currency exposure, or has been denied formal business credit. This includes retail shops, restaurants and cafés, import and export traders, service agencies, hospitality businesses, and any SME that moves money regularly and wants to do it more securely, efficiently, and intelligently.` },
      { id: 'q3', q: 'Is PayChain available right now?', a: `PayChain is currently in pre-launch. A closed beta with hand-picked merchants is launching Q2 2026, followed by a public launch in Q3 2026. You can join the waitlist at www.paychain.co.ke to secure your spot. Beta merchants receive preferential rates and early access to all features.` },
      { id: 'q4', q: 'How do I sign up?', a: `During the beta phase, you join the waitlist at www.paychain.co.ke. Fill in your name, business name, M-PESA phone number, business type, and monthly revenue range. Our team reviews all applications and contacts approved merchants before the Q2 2026 beta launch. At public launch, signup will be open to all Kenyan merchants directly through the website.` },
      { id: 'q5', q: 'What do I need to get started with PayChain?', a: `To join PayChain you need a registered Kenyan business or identifiable trading activity, a Safaricom M-PESA registered phone number, a national ID or passport for KYC verification, and a smartphone or computer to access the PayChain dashboard. No title deeds, no guarantors, no bank account required.` },
      { id: 'q6', q: 'How long does onboarding take?', a: `KYC verification and account setup is designed to take under 24 hours for most merchants. Your dedicated PayChain Virtual Account is activated upon verification approval. During the closed beta, the PayChain team provides hands-on onboarding support to every merchant — no tech experience required.` },
      { id: 'q7', q: 'Can I use PayChain alongside my existing M-PESA till?', a: `Yes. PayChain issues you a new, additional verified Virtual Account — you do not need to close or change your existing M-PESA till. Many merchants run both simultaneously during the transition period before switching fully to PayChain. The decision is entirely yours and can happen at your own pace.` },
      { id: 'q8', q: 'Is PayChain available outside Nairobi?', a: `The closed beta focuses on Nairobi and Juja. Year 2 expansion targets Mombasa, Kisumu, and Nakuru. If you are outside these areas, join the waitlist now and we will notify you when PayChain launches in your region.` },
    ],
  },
  {
    id: 'virtual-account',
    category: 'Virtual Account & Payments',
    icon: 'CreditCard',
    questions: [
      { id: 'q9', q: 'What is the PayChain Virtual Account?', a: `The PayChain Virtual Account is a verified merchant payment channel — a dedicated virtual account number registered through a licensed payment aggregator and connected to the Safaricom Daraja API. Unlike a basic M-PESA till that relies on SMS confirmations, every payment through your PayChain Virtual Account is verified against the Daraja API in real time and logged on blockchain rails for an immutable record. No SMS. No screenshots. No fraud.` },
      { id: 'q10', q: 'How does payment verification work?', a: `When a customer pays to your PayChain Virtual Account, the payment is immediately verified against the Safaricom Daraja API in under 100ms. A confirmed payment appears on your dashboard instantly with amount, timestamp, sender phone number, and transaction reference. If a payment was never sent, it simply does not appear. There is no SMS that can be faked.` },
      { id: 'q11', q: 'What payment methods can my customers use?', a: `Customers can pay via Lipa Na M-PESA, USDC on Base Network, card, or bank transfer — all verified on-chain and reflected on your dashboard in real time.` },
      { id: 'q12', q: 'What happens if a customer claims they paid but it does not show on my dashboard?', a: `If a payment was genuinely made, it will appear on your dashboard within seconds. If it does not appear, the payment was not completed on the customer's side — regardless of what their phone screen shows. Your PayChain dashboard is the single source of truth.` },
      { id: 'q13', q: 'Can I use PayChain for both in-person and online payments?', a: `Yes. Your PayChain Virtual Account works for in-person M-PESA payments and also for online payment links — usable for e-commerce, delivery orders, or invoice payments sent to customers digitally.` },
      { id: 'q14', q: 'How many transactions can I process per day?', a: `There is no daily cap imposed by PayChain. Your limits are governed by Safaricom's standard M-PESA business limits, which scale with your verified merchant tier.` },
      { id: 'q15', q: 'Will my customers need to do anything differently?', a: `No. For M-PESA payments, customers pay exactly as they always have — entering your PayChain Virtual Account number or scanning your QR code. The verification happens entirely on the backend. From the customer's perspective, nothing changes.` },
    ],
  },
  {
    id: 'inflation-shield',
    category: 'Inflation Shield & FX',
    icon: 'TrendingUp',
    questions: [
      { id: 'q16', q: 'What is the Inflation Shield?', a: `The PayChain Inflation Shield is a built-in KES-to-USDC conversion engine in your merchant dashboard. It lets you swap your KES balance to USDC stablecoin at a transparent, flat rate — protecting your purchasing power from shilling depreciation without a forex bureau, a USD bank account, or any knowledge of cryptocurrency.` },
      { id: 'q17', q: 'What is USDC and is it safe?', a: `USDC is a dollar-pegged stablecoin — always worth exactly 1 US Dollar. It is issued by Circle, a US-regulated financial company, and processes billions of dollars in transactions daily. Unlike Bitcoin or other cryptocurrencies, USDC does not fluctuate in value. PayChain uses USDC to give Kenyan merchants a stable store of value that does not depreciate with the shilling.` },
      { id: 'q18', q: 'How much does the KES to USDC swap cost?', a: `PayChain charges a flat 0.5% FX spread on all KES-to-USDC conversions. This is the total cost — no hidden fees, no exchange rate manipulation, no additional charges. You see the exact rate and amount before confirming any conversion.` },
      { id: 'q19', q: 'Can I convert my USDC back to KES?', a: `Yes. Convert USDC back to KES at any time at the same flat 0.5% rate. Your dashboard maintains a hybrid KES + USDC balance and you switch between them instantly as your business needs change.` },
      { id: 'q20', q: 'Can I pay international suppliers directly in USDC?', a: `Yes. Send USDC payments directly to international suppliers who accept USDC — without wire transfers, SWIFT fees, or bank delays. Payments settle on Base Network in under 10 seconds.` },
      { id: 'q21', q: 'Do I need a crypto wallet to use the Inflation Shield?', a: `No. PayChain manages blockchain infrastructure entirely in the background. No wallet, no seed phrase, no technical knowledge required. You see a KES balance and a USDC balance and move between them as needed.` },
      { id: 'q22', q: 'What is Base Network?', a: `Base is an Ethereum Layer 2 blockchain built and maintained by Coinbase. It processes transactions significantly faster and cheaper than the main Ethereum network while inheriting its security. PayChain uses Base for all USDC transfers because it offers near-instant settlement at a fraction of traditional international wire transfer costs.` },
    ],
  },
  {
    id: 'bulk-pay',
    category: 'Bulk Pay',
    icon: 'Users',
    questions: [
      { id: 'q23', q: 'What is PayChain Bulk Pay?', a: `PayChain Bulk Pay is a centralized outbound payment engine in your merchant dashboard. Pay your entire staff, all your suppliers, and all utility bills simultaneously in a single confirmed action — instead of individual M-PESA transfers one by one. Build your payment list once, set amounts and schedules, execute everything with one click. Every payment is logged and receipted automatically.` },
      { id: 'q24', q: 'How do I set up my payroll on Bulk Pay?', a: `Upload a CSV file with staff names, phone numbers, and amounts — or build the list directly on the dashboard. Set amounts, choose a date, select frequency. PayChain executes payroll automatically on the scheduled date and sends individual M-PESA confirmations to each staff member.` },
      { id: 'q25', q: 'Does Bulk Pay calculate PAYE automatically?', a: `Yes. Bulk Pay automatically calculates PAYE tax on employee salaries based on current KRA PAYE brackets. Calculated amounts are included in downloadable payroll reports formatted for KRA compliance.` },
      { id: 'q26', q: 'Can I pay suppliers and utility bills as well as staff?', a: `Yes. Bulk Pay handles all outbound payments — payroll, supplier invoices, utility bills (electricity, water, internet), and any recurring payments. Save each payee once, they appear in every future batch.` },
      { id: 'q27', q: 'Can I schedule payments in advance?', a: `Yes. Schedule any payment to execute automatically on a future date. Set up recurring payments — weekly, bi-weekly, or monthly — and PayChain executes them on time, notifying you when each batch completes.` },
      { id: 'q28', q: 'What happens if a payment fails in a batch?', a: `If an individual payment fails, PayChain flags it immediately with the reason. All other payments in the batch continue processing. Retry failed payments individually without re-running the entire batch.` },
      { id: 'q29', q: 'Can I set spending controls and approval workflows?', a: `Yes. Add team members with defined roles and set approval requirements for large payments. Require a second sign-off before any payment above a threshold you set — protecting against unauthorized transfers.` },
    ],
  },
  {
    id: 'cash-advance',
    category: 'Cash Advance',
    icon: 'Banknote',
    questions: [
      { id: 'q30', q: 'What is PayChain Cash Advance?', a: `PayChain Cash Advance is a data-driven working capital facility in your merchant dashboard. After 3 months of verified transaction history through your PayChain Virtual Account, your business automatically becomes eligible for an advance — limit determined entirely by your real revenue data. No collateral, no guarantors, no long application forms. Just your business data, a transparent offer, and funds in your account.` },
      { id: 'q31', q: 'How much can I borrow?', a: `Your advance limit is calculated directly from your verified PayChain transaction history. Higher and more consistent revenue means a higher limit. Limits increase with each successfully repaid advance. The exact offer — limit, origination fee, repayment terms — is presented on your dashboard before you commit.` },
      { id: 'q32', q: 'What does Cash Advance cost?', a: `PayChain charges a transparent origination fee plus a fixed repayment percentage of daily collections. The full cost — advance amount, origination fee, repayment percentage, and estimated timeline — is shown clearly before you accept. No hidden fees, no penalty interest, no early repayment charges.` },
      { id: 'q33', q: 'How does repayment work?', a: `Repayment is collected automatically as a fixed percentage of your daily PayChain collections — not a fixed monthly installment. Strong revenue = repay faster. Slow week = smaller repayment. No manual transfers, no missed payment stress.` },
      { id: 'q34', q: 'What if my business has a slow month?', a: `Because repayment is a percentage of actual daily collections, a slow month means smaller daily repayments. No minimum repayment amounts, no missed payment fees, no penalty interest for normal revenue variation.` },
      { id: 'q35', q: 'Can I repay early?', a: `Yes — with no penalty. Early repayment strengthens your Trust Score faster and accelerates eligibility for your next higher-limit advance.` },
      { id: 'q36', q: 'Does Cash Advance affect my credit record?', a: `No. PayChain Cash Advance operates entirely on your internal PayChain Trust Score. It does not interact with external credit bureaus, does not appear on your personal credit record, and has no relationship with any bank's lending criteria.` },
      { id: 'q37', q: 'Can I get a second advance before finishing repaying the first?', a: `Once a significant portion of the current advance is repaid, PayChain may present a top-up offer. A full second advance is available after full repayment of the first. Consistent repayment improves future offer terms.` },
    ],
  },
  {
    id: 'trust-score',
    category: 'Trust Score',
    icon: 'Star',
    questions: [
      { id: 'q38', q: 'What is the PayChain Trust Score?', a: `The PayChain Trust Score is a proprietary creditworthiness measure built entirely from your verified merchant activity on PayChain. It replaces the traditional credit score — designed for salaried individuals with bank accounts — with something that reflects the reality of running a business in Kenya. Visible in real time on your dashboard, growing automatically as you transact.` },
      { id: 'q39', q: 'What builds my Trust Score?', a: `Six factors: total volume of verified inbound collections, consistency and frequency of transactions over time, revenue trajectory, average transaction size, merchant tenure on the platform, and repayment history on previous Cash Advances.` },
      { id: 'q40', q: 'What does NOT affect my Trust Score?', a: `Personal credit history, property ownership, bank account balance, relationship with any financial institution, education, employment background, and personal income. Only your verified business activity on PayChain matters.` },
      { id: 'q41', q: 'How quickly does my Trust Score build?', a: `Builds from your first verified payment. After 3 months of consistent activity, most merchants reach the threshold for their first Cash Advance offer. Monitor progress and see exactly how close you are to each milestone on your dashboard.` },
      { id: 'q42', q: 'Can my Trust Score go down?', a: `Yes. Missed repayment obligations, long inactivity periods, or significant unexplained revenue drops can reduce your score. Your dashboard always shows your current score and the factors affecting it.` },
    ],
  },
  {
    id: 'security-privacy',
    category: 'Security & Privacy',
    icon: 'Shield',
    questions: [
      { id: 'q43', q: 'How secure is PayChain?', a: `PayChain uses 256-bit AES encryption on all merchant data — the same standard as the world's leading banks. Every payment is verified through the Safaricom Daraja API and settled on Base Network blockchain, creating a tamper-proof, immutable transaction record. Row Level Security policies ensure your data is only accessible to you.` },
      { id: 'q44', q: 'Who can see my transaction data?', a: `Only you, through your PayChain merchant account. PayChain uses aggregated transaction data — with your consent — to calculate your Trust Score and Cash Advance eligibility. We do not sell your data, share it with advertisers, or provide it to banks or credit bureaus.` },
      { id: 'q45', q: 'What happens to my data if I stop using PayChain?', a: `Data is retained for the legally required period under Kenyan financial regulations, then deleted. You can request a full export of your transaction data at any time before closing your account.` },
      { id: 'q46', q: 'Is PayChain compliant with Kenyan data protection laws?', a: `Yes. PayChain operates in compliance with Kenya's Data Protection Act 2019 — explicit consent, purpose limitation, appropriate technical security measures, and no transfer outside Kenya without legal justification.` },
      { id: 'q47', q: 'What happens if I lose access to my account?', a: `Contact support@paychain.co.ke with your registered business name and M-PESA phone number. Account recovery requires KYC re-verification. Our team responds within 24 hours.` },
    ],
  },
  {
    id: 'pricing-fees',
    category: 'Pricing & Fees',
    icon: 'Receipt',
    questions: [
      { id: 'q48', q: 'What does PayChain cost?', a: `No monthly fee, no setup fee, no minimum balance. PayChain earns via: transaction fee of 1.5%–2.5% on verified inbound collections, flat 0.5% FX spread on KES-to-USDC conversions, and origination fee plus revenue percentage on Cash Advances. You only pay when you use the platform. Beta merchants get locked-in preferential rates at public launch.` },
      { id: 'q49', q: 'What is the transaction fee on inbound payments?', a: `1.5%–2.5% on verified inbound collections through your PayChain Virtual Account. The exact rate depends on your merchant tier — higher volumes unlock lower rates. Beta merchants start at the lowest available rate and keep it permanently.` },
      { id: 'q50', q: 'Are there any hidden fees?', a: `No. Every fee — transaction rate, FX spread, Cash Advance cost — is shown explicitly on your dashboard before any action is taken. You will never see an unexpected deduction.` },
      { id: 'q51', q: 'What rate do beta merchants get?', a: `Beta merchants receive locked-in preferential rates maintained at public launch regardless of the standard public rate. The exact beta rate is confirmed at onboarding.` },
      { id: 'q52', q: 'Is there a minimum monthly transaction volume required?', a: `No minimum volume to maintain an account. However, consistent activity builds your Trust Score — which unlocks Cash Advance eligibility. Regular merchants get the most platform value.` },
    ],
  },
  {
    id: 'compliance-legal',
    category: 'Compliance & Legal',
    icon: 'Scale',
    questions: [
      { id: 'q53', q: 'Is PayChain regulated?', a: `PayChain is pursuing registration as a licensed payment aggregator with the Central Bank of Kenya. All operations comply with CBK guidelines, KRA e-TIMS requirements, and the Kenya Data Protection Act 2019.` },
      { id: 'q54', q: 'What is KRA e-TIMS and why does it matter?', a: `KRA's Electronic Tax Invoice Management System requires businesses to electronically generate and submit tax invoices for all taxable transactions. PayChain automatically formats every verified transaction for e-TIMS compliance — creating clean, downloadable tax records for every period with no manual data entry.` },
      { id: 'q55', q: 'Does PayChain handle VAT?', a: `PayChain's Operation Tools generate transaction records formatted for KRA e-TIMS compliance, including data required for VAT reporting. PayChain does not file taxes on your behalf — it provides the clean, structured records your accountant needs to file accurately.` },
      { id: 'q56', q: 'What happens during a KRA audit?', a: `Your PayChain transaction history provides a complete, immutable, timestamped record of every inbound and outbound payment — formatted for e-TIMS and downloadable as a full report at any time. Significantly more defensible than SMS records or manual spreadsheets.` },
      { id: 'q57', q: "Is PayChain's use of blockchain legal in Kenya?", a: `Yes. No Kenyan law prohibits blockchain for payment settlement. PayChain uses Base Network as a settlement and record-keeping layer. All customer-facing operations use familiar M-PESA infrastructure. The blockchain layer operates in the background — merchants and customers never interact with cryptocurrency directly.` },
    ],
  },
];

export const CATEGORY_ORDER = [
  'getting-started',
  'virtual-account',
  'inflation-shield',
  'bulk-pay',
  'cash-advance',
  'trust-score',
  'security-privacy',
  'pricing-fees',
  'compliance-legal',
];
