export const FAQ_DATA = [
  {
    id: 'getting-started',
    category: 'Getting Started',
    icon: 'Compass',
    questions: [
      { id: 'q1', q: 'What exactly is PayChain?', a: `PayChain is one dashboard built for Kenyan small businesses. It lets you collect payments safely through your own PayChain Paybill and virtual account (in person, via payment links, STK push, or invoices), pay your staff and suppliers all at once, and get money for your business based on your real sales, all without needing land or property, bank queues, or complicated paperwork.` },
      { id: 'q2', q: 'Who is PayChain built for?', a: `PayChain is built for any Kenyan business that collects payments, pays staff or suppliers, deals with currency changes, or has been turned down for a bank loan. This includes retail shops, restaurants and cafés, import and export traders, service agencies, hospitality businesses, and any small business that moves money regularly and wants to do it more safely and easily.` },
      { id: 'q3', q: 'Is PayChain available right now?', a: `Yes. PayChain is live: sign up directly at app.paychain.co.ke and start using your merchant dashboard right away.` },
      { id: 'q4', q: 'How do I sign up?', a: `Head to app.paychain.co.ke and create your merchant account. Fill in your name, business name, M-PESA phone number, business type, and monthly revenue range, then complete verification. You can start accepting payments as soon as your account is approved.` },
      { id: 'q5', q: 'What do I need to get started with PayChain?', a: `To join PayChain you need a Kenyan business (registered or not, as long as you're clearly trading), a Safaricom M-PESA number, a national ID or passport to verify who you are, and a smartphone or computer to access the PayChain dashboard. No title deeds, no guarantors, no bank account required.` },
      { id: 'q6', q: 'How long does onboarding take?', a: `Getting verified and set up takes under 24 hours for most merchants. Your dedicated PayChain Virtual Account switches on the moment you're approved, and the PayChain team is on hand to help, no tech experience needed.` },
      { id: 'q7', q: 'Can I use PayChain alongside my existing M-PESA till?', a: `Yes. PayChain issues you a new, additional verified Virtual Account. You do not need to close or change your existing M-PESA till. Many merchants run both simultaneously during the transition period before switching fully to PayChain. The decision is entirely yours and can happen at your own pace.` },
      { id: 'q8', q: 'Is PayChain available outside Nairobi?', a: `PayChain currently focuses on Nairobi and Juja, with expansion to Mombasa, Kisumu, and Nakuru planned next. If you are outside these areas, sign up now and we will notify you as soon as PayChain launches in your region.` },
    ],
  },
  {
    id: 'virtual-account',
    category: 'Virtual Account & Payments',
    icon: 'CreditCard',
    questions: [
      { id: 'q9', q: 'What is the PayChain Virtual Account?', a: `Every PayChain merchant gets a dedicated PayChain Paybill and virtual account, a payment channel registered through our licensed banking partner, NCBA Bank. Unlike a basic M-PESA till that relies on SMS confirmations, every payment through it is verified in real time and logged for an immutable record. No SMS. No screenshots. No fraud.` },
      { id: 'q10', q: 'How does payment verification work?', a: `When a customer pays to your PayChain Paybill or virtual account, NCBA Bank confirms it instantly, in a fraction of a second. A confirmed payment shows up on your dashboard right away with the amount, time, sender's phone number, and reference. If a payment was never actually sent, it simply won't appear. There's no SMS screenshot that can be faked.` },
      { id: 'q11', q: 'What payment methods can my customers use?', a: `Customers can pay via Lipa Na M-PESA to your Paybill or virtual account, a payment link you send them (even over WhatsApp), an STK push straight to their phone, a professional invoice, card, or bank transfer, all verified and reflected on your dashboard in real time.` },
      { id: 'q12', q: 'What happens if a customer claims they paid but it does not show on my dashboard?', a: `If a payment was genuinely made, it will appear on your dashboard within seconds. If it does not appear, the payment was not completed on the customer's side, regardless of what their phone screen shows. Your PayChain dashboard is the single source of truth.` },
      { id: 'q13', q: 'Can I use PayChain for both in-person and online payments?', a: `Yes. Your PayChain Paybill and virtual account work for in-person M-PESA payments, and for online collection too: send a payment link to a customer (even over WhatsApp) for e-commerce, delivery orders, or one-off sales, and it settles instantly the moment they pay. You can also send an STK push directly to a customer's phone to prompt them to pay, or send them a professional invoice with a payable link built in.` },
      { id: 'q14', q: 'How many transactions can I process per day?', a: `PayChain doesn't set a daily limit. Your limit comes from our banking partner NCBA's standard rules, which get bigger as you use PayChain more and build up your history.` },
      { id: 'q15', q: 'Will my customers need to do anything differently?', a: `No. For M-PESA payments, customers pay exactly as they always have, entering your PayChain Virtual Account number or scanning your QR code. The verification happens entirely on the backend. From the customer's perspective, nothing changes.` },
    ],
  },
  {
    id: 'inflation-shield',
    category: 'Inflation Shield & FX',
    icon: 'TrendingUp',
    questions: [
      { id: 'q16', q: 'What is the Inflation Shield?', a: `The PayChain Inflation Shield is a feature we're currently building: a way to change your shillings into USDC (a digital dollar that always keeps its $1 value), for one clear flat fee, so your money doesn't lose value as the shilling weakens. No forex bureau, no need to understand crypto. It's still being built and not yet available to merchants.` },
      { id: 'q22', q: 'When will the Inflation Shield be available?', a: `We don't have a firm launch date yet. It's actively in development. Sign up to PayChain and join the waitlist on the Inflation Shield page to be notified the moment it opens up.` },
    ],
  },
  {
    id: 'bulk-pay',
    category: 'Bulk Pay',
    icon: 'Users',
    questions: [
      { id: 'q23', q: 'What is PayChain Bulk Pay?', a: `PayChain Bulk Pay is a centralized outbound payment engine in your merchant dashboard. Pay your entire staff, all your suppliers, and all utility bills simultaneously in a single confirmed action, instead of individual M-PESA transfers one by one. Build your payment list once, set amounts and schedules, execute everything with one click. Every payment is logged and receipted automatically.` },
      { id: 'q24', q: 'How do I set up my payroll on Bulk Pay?', a: `Upload a CSV file with staff names, phone numbers, and amounts, or build the list directly on the dashboard. Set amounts, choose a date, select frequency. PayChain executes payroll automatically on the scheduled date and sends individual M-PESA confirmations to each staff member.` },
      { id: 'q25', q: 'Does Bulk Pay calculate PAYE automatically?', a: `Yes. Bulk Pay works out PAYE tax on employee salaries automatically, using the current government tax rates. The amounts show up in your downloadable payroll reports.` },
      { id: 'q26', q: 'Can I pay suppliers and utility bills as well as staff?', a: `Yes. Bulk Pay handles all outbound payments: payroll, suppliers, contractors, KPLC tokens (prepaid or postpaid), water, internet, and any other recurring payments, all in one click. Save each payee once, they appear in every future batch.` },
      { id: 'q27', q: 'Can I schedule payments in advance?', a: `Yes. Schedule any payment to execute automatically on a future date. Set up recurring payments (weekly, bi-weekly, or monthly) and PayChain executes them on time, notifying you when each batch completes.` },
      { id: 'q28', q: 'What happens if a payment fails in a batch?', a: `If an individual payment fails, PayChain flags it immediately with the reason. All other payments in the batch continue processing. Retry failed payments individually without re-running the entire batch.` },
      { id: 'q29', q: 'Can I set spending controls and approval workflows?', a: `Yes. Add team members with defined roles and set approval requirements for large payments. Require a second sign-off before any payment above a threshold you set, protecting against unauthorized transfers.` },
    ],
  },
  {
    id: 'cash-advance',
    category: 'Cash Advance',
    icon: 'Banknote',
    questions: [
      { id: 'q30', q: 'What is PayChain Cash Advance?', a: `PayChain Cash Advance is money for your business, built into your dashboard. After 3 months of using your PayChain Virtual Account, your business automatically qualifies for an advance, with how much you get based entirely on your real sales. No land or property, no guarantors, no long forms to fill. Just your own business history, a clear offer, and money in your account.` },
      { id: 'q31', q: 'How much can I borrow?', a: `How much you can borrow is worked out directly from your PayChain sales history. Higher and steadier sales means a bigger amount. It grows every time you successfully pay back an advance. The exact offer (amount, one-time fee, how you pay it back) is shown on your dashboard before you accept.` },
      { id: 'q32', q: 'What does Cash Advance cost?', a: `PayChain charges one clear one-time fee, plus a fixed share of what you sell each day until it's repaid. The full cost (amount, fee, share, and roughly how long it'll take) is shown clearly before you accept. No hidden fees, no extra interest, no charge for paying early.` },
      { id: 'q33', q: 'How does repayment work?', a: `Repayment is taken automatically as a fixed share of what you sell each day through PayChain, not a fixed amount every month. Good sales = you repay faster. Slow week = a smaller repayment. No manual transfers, no stress about missing a payment.` },
      { id: 'q34', q: 'What if my business has a slow month?', a: `Since repayment is a share of what you actually sell each day, a slow month simply means smaller daily repayments. No minimum amount, no missed-payment fees, no penalty for a normal slow patch.` },
      { id: 'q35', q: 'Can I repay early?', a: `Yes, with no penalty. Paying back early builds your Trust Score faster and gets you a bigger next offer, sooner.` },
      { id: 'q36', q: 'Does Cash Advance affect my credit record?', a: `No. PayChain Cash Advance works entirely off your own PayChain Trust Score. It has nothing to do with CRB, doesn't show up on your personal credit record, and has no connection to any bank's lending rules.` },
      { id: 'q37', q: 'Can I get a second advance before finishing repaying the first?', a: `Once you've paid back a good chunk of your current advance, PayChain may offer you a top-up. A full second advance becomes available once the first is fully repaid. Paying back reliably gets you better offers next time.` },
    ],
  },
  {
    id: 'trust-score',
    category: 'Trust Score',
    icon: 'Star',
    questions: [
      { id: 'q38', q: 'What is the PayChain Trust Score?', a: `The PayChain Trust Score is our own way of measuring how trustworthy your business is, built entirely from your own activity on PayChain. It replaces the traditional credit score (which is really built for salaried people with bank accounts) with something that actually reflects running a business in Kenya. You can watch it grow live on your dashboard as you sell.` },
      { id: 'q39', q: 'What builds my Trust Score?', a: `Six things: how much money you've collected in total, how regularly you get paid, whether your sales are growing or steady, your average customer payment size, how long you've been on PayChain, and whether you've paid back past Cash Advances on time.` },
      { id: 'q40', q: 'What does NOT affect my Trust Score?', a: `Your personal credit history, whether you own property, your bank balance, your relationship with any bank, your education, or your personal income. Only your real business activity on PayChain matters.` },
      { id: 'q41', q: 'How quickly does my Trust Score build?', a: `It starts growing from your very first verified payment. After 3 months of steady activity, most merchants reach the point where they get their first Cash Advance offer. You can watch your progress and see how close you are on your dashboard.` },
      { id: 'q42', q: 'Can my Trust Score go down?', a: `Yes. Missed repayment obligations, long inactivity periods, or significant unexplained revenue drops can reduce your score. Your dashboard always shows your current score and the factors affecting it.` },
    ],
  },
  {
    id: 'security-privacy',
    category: 'Security & Privacy',
    icon: 'Shield',
    questions: [
      { id: 'q43', q: 'How secure is PayChain?', a: `PayChain locks down all your business data with the same level of encryption the world's biggest banks use. Every payment is confirmed through NCBA Bank, so your transaction record can't be faked or changed after the fact. Strict access rules make sure nobody but you can see your own data.` },
      { id: 'q44', q: 'Who can see my transaction data?', a: `Only you, through your PayChain merchant account. With your permission, PayChain uses your transaction data to work out your Trust Score and Cash Advance eligibility. We do not sell your data, share it with advertisers, or hand it to banks or CRB.` },
      { id: 'q45', q: 'What happens to my data if I stop using PayChain?', a: `Data is retained for the legally required period under Kenyan financial regulations, then deleted. You can request a full export of your transaction data at any time before closing your account.` },
      { id: 'q46', q: 'Is PayChain compliant with Kenyan data protection laws?', a: `Yes. PayChain Financial Services Ltd is officially registered with Kenya's Office of the Data Protection Commissioner (ODPC), and follows the Data Protection Act 2019: we ask your permission before using your data, only use it for what we said we would, protect it properly, and never send it outside Kenya without good legal reason.` },
      { id: 'q47', q: 'What happens if I lose access to my account?', a: `Contact support@paychain.co.ke with your registered business name and M-PESA phone number. Account recovery requires KYC re-verification. Our team responds within 24 hours.` },
    ],
  },
  {
    id: 'pricing-fees',
    category: 'Pricing & Fees',
    icon: 'Receipt',
    questions: [
      { id: 'q48', q: 'What does PayChain cost?', a: `No monthly fee, no setup fee, no minimum balance to keep. PayChain earns a small fee of 1.5% to 2.5% on money you collect, plus a one-time fee and a small share on Cash Advances. You only pay when you actually use it. Merchants who join early keep a better rate for good, even after the rate changes for everyone else.` },
      { id: 'q49', q: 'What is the transaction fee on money you receive?', a: `1.5% to 2.5% on the money you collect through your PayChain account. The exact rate depends on your merchant level — the more you collect, the lower your rate. Merchants who join early get the lowest rate available and keep it for good.` },
      { id: 'q50', q: 'Are there any hidden fees?', a: `No. Every fee (transaction rate, currency exchange fee, Cash Advance cost) is shown clearly on your dashboard before anything happens. You'll never see a surprise deduction.` },
      { id: 'q51', q: 'What rate do beta merchants get?', a: `Merchants who join now get a better rate that stays locked in for good, even after PayChain fully launches and rates for everyone else may change. The exact rate is confirmed when you sign up.` },
      { id: 'q52', q: 'Is there a minimum monthly transaction volume required?', a: `No minimum volume to maintain an account. However, consistent activity builds your Trust Score, which unlocks Cash Advance eligibility. Regular merchants get the most platform value.` },
    ],
  },
  {
    id: 'compliance-legal',
    category: 'Compliance & Legal',
    icon: 'Scale',
    questions: [
      { id: 'q53', q: 'Is PayChain regulated?', a: `PayChain is in the process of becoming a licensed payment company under the Central Bank of Kenya (CBK). Everything we do follows CBK's rules and Kenya's Data Protection Act 2019.` },
      { id: 'q57', q: "Is PayChain's use of blockchain legal in Kenya?", a: `Yes. No Kenyan law bans using blockchain (a secure digital record-keeping system) to move money. It's the technology we're building the upcoming Inflation Shield feature on. It has nothing to do with your regular M-PESA payments, which run entirely on familiar M-PESA and NCBA Bank systems. Once the Inflation Shield launches, the blockchain part happens quietly in the background — merchants and customers won't need to understand or deal with crypto directly.` },
    ],
  },
];

export const CATEGORY_ORDER = [
  'getting-started',
  'virtual-account',
  'inflation-shield',
  'bulk-pay',
  'cash-advance',
  'trust-score',
  'security-privacy',
  'pricing-fees',
  'compliance-legal',
];
