export const FAQ_DATA = [
  {
    id: 'getting-started',
    category: 'Getting Started',
    icon: 'Compass',
    questions: [
      { id: 'q1', q: 'What exactly is PayChain?', a: `PayChain is a hybrid merchant operating system built for Kenyan SMEs. It gives you a single dashboard to collect payments securely through a dedicated PayChain Paybill and virtual account (in person, via payment links, STK push, or invoices), pay staff and suppliers in bulk, and access working capital based on your real transaction history, all without collateral, bank queues, or complex paperwork.` },
      { id: 'q2', q: 'Who is PayChain built for?', a: `PayChain is built for any Kenyan business that collects payments, pays staff or suppliers, deals with currency exposure, or has been denied formal business credit. This includes retail shops, restaurants and cafés, import and export traders, service agencies, hospitality businesses, and any SME that moves money regularly and wants to do it more securely, efficiently, and intelligently.` },
      { id: 'q3', q: 'Is PayChain available right now?', a: `Yes. PayChain is live: sign up directly at app.paychain.co.ke and start using your merchant dashboard right away.` },
      { id: 'q4', q: 'How do I sign up?', a: `Head to app.paychain.co.ke and create your merchant account. Fill in your name, business name, M-PESA phone number, business type, and monthly revenue range, then complete verification. You can start accepting payments as soon as your account is approved.` },
      { id: 'q5', q: 'What do I need to get started with PayChain?', a: `To join PayChain you need a registered Kenyan business or identifiable trading activity, a Safaricom M-PESA registered phone number, a national ID or passport for KYC verification, and a smartphone or computer to access the PayChain dashboard. No title deeds, no guarantors, no bank account required.` },
      { id: 'q6', q: 'How long does onboarding take?', a: `KYC verification and account setup is designed to take under 24 hours for most merchants. Your dedicated PayChain Virtual Account is activated upon verification approval, and the PayChain team is on hand to help with onboarding, no tech experience required.` },
      { id: 'q7', q: 'Can I use PayChain alongside my existing M-PESA till?', a: `Yes. PayChain issues you a new, additional verified Virtual Account. You do not need to close or change your existing M-PESA till. Many merchants run both simultaneously during the transition period before switching fully to PayChain. The decision is entirely yours and can happen at your own pace.` },
      { id: 'q8', q: 'Is PayChain available outside Nairobi?', a: `PayChain currently focuses on Nairobi and Juja, with expansion to Mombasa, Kisumu, and Nakuru planned next. If you are outside these areas, sign up now and we will notify you as soon as PayChain launches in your region.` },
    ],
  },
  {
    id: 'virtual-account',
    category: 'Virtual Account & Payments',
    icon: 'CreditCard',
    questions: [
      { id: 'q9', q: 'What is the PayChain Virtual Account?', a: `Every PayChain merchant gets a dedicated PayChain Paybill and virtual account, a payment channel registered through our licensed banking partner, NCBA Bank. Unlike a basic M-PESA till that relies on SMS confirmations, every payment through it is verified in real time and logged for an immutable record. No SMS. No screenshots. No fraud.` },
      { id: 'q10', q: 'How does payment verification work?', a: `When a customer pays to your PayChain Paybill or virtual account, the payment is immediately verified through our NCBA Bank integration in under 100ms. A confirmed payment appears on your dashboard instantly with amount, timestamp, sender phone number, and transaction reference. If a payment was never sent, it simply does not appear. There is no SMS that can be faked.` },
      { id: 'q11', q: 'What payment methods can my customers use?', a: `Customers can pay via Lipa Na M-PESA to your Paybill or virtual account, a payment link you send them (even over WhatsApp), an STK push straight to their phone, a professional invoice, card, or bank transfer, all verified and reflected on your dashboard in real time.` },
      { id: 'q12', q: 'What happens if a customer claims they paid but it does not show on my dashboard?', a: `If a payment was genuinely made, it will appear on your dashboard within seconds. If it does not appear, the payment was not completed on the customer's side, regardless of what their phone screen shows. Your PayChain dashboard is the single source of truth.` },
      { id: 'q13', q: 'Can I use PayChain for both in-person and online payments?', a: `Yes. Your PayChain Paybill and virtual account work for in-person M-PESA payments, and for online collection too: send a payment link to a customer (even over WhatsApp) for e-commerce, delivery orders, or one-off sales, and it settles instantly the moment they pay. You can also send an STK push directly to a customer's phone to prompt them to pay, or send them a professional invoice with a payable link built in.` },
      { id: 'q14', q: 'How many transactions can I process per day?', a: `There is no daily cap imposed by PayChain. Your limits are governed by our banking partner NCBA's standard transaction tariffs, which scale with your verified merchant tier.` },
      { id: 'q15', q: 'Will my customers need to do anything differently?', a: `No. For M-PESA payments, customers pay exactly as they always have, entering your PayChain Virtual Account number or scanning your QR code. The verification happens entirely on the backend. From the customer's perspective, nothing changes.` },
    ],
  },
  {
    id: 'inflation-shield',
    category: 'Inflation Shield & FX',
    icon: 'TrendingUp',
    questions: [
      { id: 'q16', q: 'What is the Inflation Shield?', a: `The PayChain Inflation Shield is a stablecoin protection feature we're currently building: a way to swap your KES balance to USDC (a dollar-pegged stablecoin) at a transparent, flat rate, protecting your purchasing power from shilling depreciation without a forex bureau or any crypto knowledge required. It's in development and not yet available to merchants.` },
      { id: 'q22', q: 'When will the Inflation Shield be available?', a: `We don't have a firm launch date yet. It's actively in development. Sign up to PayChain and join the waitlist on the Inflation Shield page to be notified the moment it opens up.` },
    ],
  },
  {
    id: 'bulk-pay',
    category: 'Bulk Pay',
    icon: 'Users',
    questions: [
      { id: 'q23', q: 'What is PayChain Bulk Pay?', a: `PayChain Bulk Pay is a centralized outbound payment engine in your merchant dashboard. Pay your entire staff, all your suppliers, and all utility bills simultaneously in a single confirmed action, instead of individual M-PESA transfers one by one. Build your payment list once, set amounts and schedules, execute everything with one click. Every payment is logged and receipted automatically.` },
      { id: 'q24', q: 'How do I set up my payroll on Bulk Pay?', a: `Upload a CSV file with staff names, phone numbers, and amounts, or build the list directly on the dashboard. Set amounts, choose a date, select frequency. PayChain executes payroll automatically on the scheduled date and sends individual M-PESA confirmations to each staff member.` },
      { id: 'q25', q: 'Does Bulk Pay calculate PAYE automatically?', a: `Yes. Bulk Pay automatically calculates PAYE tax on employee salaries based on current PAYE brackets. Calculated amounts are included in downloadable payroll reports.` },
      { id: 'q26', q: 'Can I pay suppliers and utility bills as well as staff?', a: `Yes. Bulk Pay handles all outbound payments: payroll, suppliers, contractors, KPLC tokens (prepaid or postpaid), water, internet, and any other recurring payments, all in one click. Save each payee once, they appear in every future batch.` },
      { id: 'q27', q: 'Can I schedule payments in advance?', a: `Yes. Schedule any payment to execute automatically on a future date. Set up recurring payments (weekly, bi-weekly, or monthly) and PayChain executes them on time, notifying you when each batch completes.` },
      { id: 'q28', q: 'What happens if a payment fails in a batch?', a: `If an individual payment fails, PayChain flags it immediately with the reason. All other payments in the batch continue processing. Retry failed payments individually without re-running the entire batch.` },
      { id: 'q29', q: 'Can I set spending controls and approval workflows?', a: `Yes. Add team members with defined roles and set approval requirements for large payments. Require a second sign-off before any payment above a threshold you set, protecting against unauthorized transfers.` },
    ],
  },
  {
    id: 'cash-advance',
    category: 'Cash Advance',
    icon: 'Banknote',
    questions: [
      { id: 'q30', q: 'What is PayChain Cash Advance?', a: `PayChain Cash Advance is a data-driven working capital facility in your merchant dashboard. After 3 months of verified transaction history through your PayChain Virtual Account, your business automatically becomes eligible for an advance: limit determined entirely by your real revenue data. No collateral, no guarantors, no long application forms. Just your business data, a transparent offer, and funds in your account.` },
      { id: 'q31', q: 'How much can I borrow?', a: `Your advance limit is calculated directly from your verified PayChain transaction history. Higher and more consistent revenue means a higher limit. Limits increase with each successfully repaid advance. The exact offer (limit, origination fee, repayment terms) is presented on your dashboard before you commit.` },
      { id: 'q32', q: 'What does Cash Advance cost?', a: `PayChain charges a transparent origination fee plus a fixed repayment percentage of daily collections. The full cost (advance amount, origination fee, repayment percentage, and estimated timeline) is shown clearly before you accept. No hidden fees, no penalty interest, no early repayment charges.` },
      { id: 'q33', q: 'How does repayment work?', a: `Repayment is collected automatically as a fixed percentage of your daily PayChain collections, not a fixed monthly installment. Strong revenue = repay faster. Slow week = smaller repayment. No manual transfers, no missed payment stress.` },
      { id: 'q34', q: 'What if my business has a slow month?', a: `Because repayment is a percentage of actual daily collections, a slow month means smaller daily repayments. No minimum repayment amounts, no missed payment fees, no penalty interest for normal revenue variation.` },
      { id: 'q35', q: 'Can I repay early?', a: `Yes, with no penalty. Early repayment strengthens your Trust Score faster and accelerates eligibility for your next higher-limit advance.` },
      { id: 'q36', q: 'Does Cash Advance affect my credit record?', a: `No. PayChain Cash Advance operates entirely on your internal PayChain Trust Score. It does not interact with external credit bureaus, does not appear on your personal credit record, and has no relationship with any bank's lending criteria.` },
      { id: 'q37', q: 'Can I get a second advance before finishing repaying the first?', a: `Once a significant portion of the current advance is repaid, PayChain may present a top-up offer. A full second advance is available after full repayment of the first. Consistent repayment improves future offer terms.` },
    ],
  },
  {
    id: 'trust-score',
    category: 'Trust Score',
    icon: 'Star',
    questions: [
      { id: 'q38', q: 'What is the PayChain Trust Score?', a: `The PayChain Trust Score is a proprietary creditworthiness measure built entirely from your verified merchant activity on PayChain. It replaces the traditional credit score, designed for salaried individuals with bank accounts, with something that reflects the reality of running a business in Kenya. Visible in real time on your dashboard, growing automatically as you transact.` },
      { id: 'q39', q: 'What builds my Trust Score?', a: `Six factors: total volume of verified inbound collections, consistency and frequency of transactions over time, revenue trajectory, average transaction size, merchant tenure on the platform, and repayment history on previous Cash Advances.` },
      { id: 'q40', q: 'What does NOT affect my Trust Score?', a: `Personal credit history, property ownership, bank account balance, relationship with any financial institution, education, employment background, and personal income. Only your verified business activity on PayChain matters.` },
      { id: 'q41', q: 'How quickly does my Trust Score build?', a: `Builds from your first verified payment. After 3 months of consistent activity, most merchants reach the threshold for their first Cash Advance offer. Monitor progress and see exactly how close you are to each milestone on your dashboard.` },
      { id: 'q42', q: 'Can my Trust Score go down?', a: `Yes. Missed repayment obligations, long inactivity periods, or significant unexplained revenue drops can reduce your score. Your dashboard always shows your current score and the factors affecting it.` },
    ],
  },
  {
    id: 'security-privacy',
    category: 'Security & Privacy',
    icon: 'Shield',
    questions: [
      { id: 'q43', q: 'How secure is PayChain?', a: `PayChain uses 256-bit AES encryption on all merchant data: the same standard as the world's leading banks. Every payment is verified through our NCBA Bank integration, creating a tamper-proof, immutable transaction record. Row Level Security policies ensure your data is only accessible to you.` },
      { id: 'q44', q: 'Who can see my transaction data?', a: `Only you, through your PayChain merchant account. PayChain uses aggregated transaction data, with your consent, to calculate your Trust Score and Cash Advance eligibility. We do not sell your data, share it with advertisers, or provide it to banks or credit bureaus.` },
      { id: 'q45', q: 'What happens to my data if I stop using PayChain?', a: `Data is retained for the legally required period under Kenyan financial regulations, then deleted. You can request a full export of your transaction data at any time before closing your account.` },
      { id: 'q46', q: 'Is PayChain compliant with Kenyan data protection laws?', a: `Yes. PayChain Financial Services Ltd is a registered Data Controller with Kenya's Office of the Data Protection Commissioner (ODPC), and operates in full compliance with the Data Protection Act 2019: explicit consent, purpose limitation, appropriate technical security measures, and no transfer outside Kenya without legal justification.` },
      { id: 'q47', q: 'What happens if I lose access to my account?', a: `Contact support@paychain.co.ke with your registered business name and M-PESA phone number. Account recovery requires KYC re-verification. Our team responds within 24 hours.` },
    ],
  },
  {
    id: 'pricing-fees',
    category: 'Pricing & Fees',
    icon: 'Receipt',
    questions: [
      { id: 'q48', q: 'What does PayChain cost?', a: `No monthly fee, no setup fee, no minimum balance. PayChain earns via: transaction fee of 1.5%–2.5% on verified inbound collections, and origination fee plus revenue percentage on Cash Advances. You only pay when you use the platform. Beta merchants get locked-in preferential rates at public launch.` },
      { id: 'q49', q: 'What is the transaction fee on inbound payments?', a: `1.5%–2.5% on verified inbound collections through your PayChain Virtual Account. The exact rate depends on your merchant tier. Higher volumes unlock lower rates. Beta merchants start at the lowest available rate and keep it permanently.` },
      { id: 'q50', q: 'Are there any hidden fees?', a: `No. Every fee (transaction rate, FX spread, Cash Advance cost) is shown explicitly on your dashboard before any action is taken. You will never see an unexpected deduction.` },
      { id: 'q51', q: 'What rate do beta merchants get?', a: `Beta merchants receive locked-in preferential rates maintained at public launch regardless of the standard public rate. The exact beta rate is confirmed at onboarding.` },
      { id: 'q52', q: 'Is there a minimum monthly transaction volume required?', a: `No minimum volume to maintain an account. However, consistent activity builds your Trust Score, which unlocks Cash Advance eligibility. Regular merchants get the most platform value.` },
    ],
  },
  {
    id: 'compliance-legal',
    category: 'Compliance & Legal',
    icon: 'Scale',
    questions: [
      { id: 'q53', q: 'Is PayChain regulated?', a: `PayChain is pursuing registration as a licensed payment aggregator with the Central Bank of Kenya. All operations comply with CBK guidelines and the Kenya Data Protection Act 2019.` },
      { id: 'q57', q: "Is PayChain's use of blockchain legal in Kenya?", a: `Yes. No Kenyan law prohibits blockchain for payment settlement. Blockchain (Base Network) is the settlement layer we're building for the upcoming Inflation Shield feature. It's not used for regular M-PESA collections, which run entirely on familiar M-PESA and NCBA Bank infrastructure. When the Inflation Shield launches, the blockchain layer will operate in the background. Merchants and customers won't need to interact with cryptocurrency directly.` },
    ],
  },
];

export const CATEGORY_ORDER = [
  'getting-started',
  'virtual-account',
  'inflation-shield',
  'bulk-pay',
  'cash-advance',
  'trust-score',
  'security-privacy',
  'pricing-fees',
  'compliance-legal',
];
